import {
  getCuratedExerciseCatalog,
  getExerciseInsight,
  getLocalizedExerciseName,
  SupportedLanguage,
} from "@/lib/exerciseCatalog";

export type ExerciseOption = {
  id: string;
  name: string;
  canonicalName: string;
  source: "video-index" | "core";
};

export type EquipmentAccess = "gym" | "dumbbells" | "bodyweight";
type ExerciseRole = "main" | "warmup" | "cooldown";

const CORE_EXERCISES: string[] = [
  // Main strength / hypertrophy pool
  "Back Squat",
  "Front Squat",
  "Goblet Squat",
  "Leg Press",
  "Romanian Deadlift",
  "Dumbbell Romanian Deadlift",
  "Deadlift",
  "Trap Bar Deadlift",
  "Hip Thrust",
  "Glute Bridge",
  "Bench Press",
  "Incline Dumbbell Press",
  "Dumbbell Floor Press",
  "Push-Up",
  "Pike Push-Up",
  "Overhead Press",
  "Dumbbell Shoulder Press",
  "Landmine Press",
  "Seated Cable Row",
  "One-Arm Dumbbell Row",
  "Chest-Supported Row",
  "Lat Pulldown",
  "Pull-Up",
  "Inverted Row",
  "Face Pull",
  "Biceps Curl",
  "Triceps Extension",
  "Calf Raise",
  "Split Squat",
  "Bulgarian Split Squat",
  "Reverse Lunge",
  "Walking Lunge",
  "Step-Up",
  "Step-Down",
  "Plank",
  "Side Plank",
  "Dead Bug",
  "Mountain Climbers",
  "Farmer Carry",
  "Arnold Press",
  "Chest Fly",
  "Cable Fly",
  "Hammer Curl",
  "Skull Crusher",
  "Single-Leg Romanian Deadlift",
  "Leg Curl",
  "Leg Extension",
  "Seated Calf Raise",
  "Standing Calf Raise",

  // Warm-up catalog
  "Joint Mobility Primer",
  "Activation and Ramp-Up Sets",
  "Dynamic Hip Opener",
  "Ankle Dorsiflexion Drill",
  "Thoracic Spine Rotation",
  "Scapular Wall Slide",
  "Band Pull-Apart",
  "Cat-Cow Mobility",
  "World's Greatest Stretch",
  "Hamstring Dynamic Sweep",
  "Adductor Rockback",
  "Bear Plank Breathing",
  "90-90 Hip Switch",
  "Walking Knee Hug",
  "Walking Quad Pull",
  "Spinal Segmentation Drill",
  "Glute Activation Bridge",

  // Cooldown / stretching catalog
  "Breathing Downregulation",
  "Targeted Stretching",
  "Hip Flexor Stretch",
  "Calf Stretch Wall",
  "Pec Doorway Stretch",
  "Lat Stretch Bench",
  "Quadriceps Stretch Standing",
  "Hamstring Stretch Standing",
  "Chest Stretch Doorway",
  "Thoracic Extension Stretch",
  "Child Pose Breathing",

  // Spanish aliases commonly generated by AI
  "Movilidad Articular Inicial",
  "Activacion y Series de Aproximacion",
  "Vuelta a la Calma Respiratoria",
  "Estiramiento Dirigido",
];

const EQUIVALENCE_GROUPS: string[][] = [
  [
    "back squat",
    "front squat",
    "goblet squat",
    "bodyweight squat",
    "squat barbell",
    "squat dumbbell",
    "squat lever",
    "v squat lever",
    "leg press",
    "trx assisted squat",
  ],
  [
    "deadlift",
    "romanian deadlift",
    "dumbbell romanian deadlift",
    "straight leg deadlift barbell",
    "straight leg deadlift dumbbell",
    "sumo deadlift barbell",
    "trap bar deadlift",
    "hip thrust",
    "glute bridge",
  ],
  [
    "bench press",
    "incline dumbbell press",
    "dumbbell floor press",
    "push up",
    "trx chest press",
    "single arm incline press cable",
  ],
  [
    "overhead press",
    "dumbbell shoulder press",
    "pike push up",
    "standing press cable",
    "twisting overhead press cable",
    "landmine press",
    "trx y fly",
  ],
  [
    "seated cable row",
    "one arm dumbbell row",
    "chest supported row",
    "standing row lever",
    "standing cross row cable",
    "inverted row",
    "trx row",
    "trx y fly",
  ],
  [
    "lat pulldown",
    "pull up",
    "underhand pulldown cable",
    "underhand pull up cable",
  ],
  [
    "split squat",
    "bulgarian split squat",
    "reverse lunge",
    "walking lunge",
    "split squat wide",
    "single leg split squat",
    "split squat single leg dumbbell",
    "split squat single leg cable",
    "step up",
    "step ups",
    "step ups dumbbell",
    "step ups cable",
    "step ups barbell",
    "step down",
    "trx assisted squat",
    "trx split squat",
    "side lunge dumbbell",
    "side lunge barbell",
  ],
  [
    "plank",
    "side plank",
    "dead bug",
    "mountain climbers",
    "trx pike",
    "pilates hundred",
    "pilates roll up",
    "pilates single leg stretch",
    "sun salutation flow",
    "weighted crunch",
    "side crunch",
    "standing crunch cable",
  ],
  [
    "glute bridge",
    "hip thrust",
    "pilates shoulder bridge",
    "trx hamstring curl",
    "leg curl",
  ],
  [
    "biceps curl",
    "zottman curl",
    "hammer curl",
  ],
  [
    "triceps extension",
    "triceps extension seated dumbbell",
    "triceps extension seated barbell",
    "triceps extension overhead cable",
    "triceps pushdown cable",
    "triceps pushdown rope cable",
    "skull crusher",
  ],
  [
    "calf raise",
    "seated calf raise",
    "standing calf raise",
    "calf stretch seated with towel",
    "calf stretch wall",
  ],
  [
    "joint mobility primer",
    "movilidad articular inicial",
    "mobility primer",
    "cat cow mobility",
    "thoracic spine rotation",
    "ankle dorsiflexion drill",
    "dynamic hip opener",
    "pilates swan",
    "yoga cobra pose",
    "yoga downward dog",
    "yoga low lunge stretch",
    "yoga pigeon stretch",
    "sun salutation flow",
  ],
  [
    "activation and ramp up sets",
    "activacion y series de aproximacion",
    "band pull apart",
    "scapular wall slide",
    "glute activation bridge",
    "bear plank breathing",
  ],
  [
    "breathing downregulation",
    "vuelta a la calma respiratoria",
    "breathing stretch",
    "child pose breathing",
  ],
  [
    "targeted stretching",
    "estiramiento dirigido",
    "hip flexor stretch",
    "pec doorway stretch",
    "lat stretch bench",
    "quadriceps stretch standing",
    "hamstring stretch standing",
    "thoracic extension stretch",
  ],
];

const ROLE_WARMUP_HINTS = [
  "warm up",
  "warmup",
  "movilidad",
  "mobility",
  "activation",
  "activacion",
  "drill",
  "primer",
  "ramp",
  "aproximacion",
  "dynamic",
  "dinamico",
  "prep",
];

const ROLE_COOLDOWN_HINTS = [
  "cool down",
  "cooldown",
  "enfriamiento",
  "vuelta a la calma",
  "stretch",
  "estiramiento",
  "breathing downregulation",
  "respiratoria",
  "recovery",
  "recuperacion",
];

const normalize = (value: string): string => {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
};

const slugify = (value: string): string => normalize(value).replace(/\s+/g, "-");

const DATABASE_CACHE: Record<SupportedLanguage, ExerciseOption[] | null> = {
  en: null,
  es: null,
};

const isRoleHint = (normalizedName: string, hints: string[]): boolean => {
  return hints.some((hint) => normalizedName.includes(hint));
};

const inferExerciseRole = (
  exerciseName: string,
  movementPattern: ReturnType<typeof getExerciseInsight>["movementPattern"]
): ExerciseRole => {
  const normalizedName = normalize(exerciseName);

  if (isRoleHint(normalizedName, ROLE_COOLDOWN_HINTS)) {
    return "cooldown";
  }

  if (isRoleHint(normalizedName, ROLE_WARMUP_HINTS) || movementPattern === "mobility") {
    return "warmup";
  }

  return "main";
};

const isRoleCompatible = (targetRole: ExerciseRole, candidateRole: ExerciseRole): boolean => {
  return targetRole === candidateRole;
};

const buildEquivalenceIndex = () => {
  const index = new Map<string, string[]>();
  EQUIVALENCE_GROUPS.forEach((group) => {
    const normalizedGroup = group.map((item) => normalize(item));
    normalizedGroup.forEach((item) => {
      index.set(item, normalizedGroup);
    });
  });
  return index;
};

const EQUIVALENCE_INDEX = buildEquivalenceIndex();

const buildDatabase = (language: SupportedLanguage): ExerciseOption[] => {
  const map = new Map<string, ExerciseOption>();
  const catalog = getCuratedExerciseCatalog();

  catalog.forEach((entry) => {
    const key = normalize(entry.nameEn);
    if (!key) {
      return;
    }

    map.set(key, {
      id: entry.id || slugify(entry.nameEn),
      name: language === "es" ? entry.nameEs : entry.nameEn,
      canonicalName: entry.nameEn,
      source: "video-index",
    });
  });

  CORE_EXERCISES.forEach((exerciseName) => {
    const key = normalize(exerciseName);
    if (!map.has(key)) {
      map.set(key, {
        id: slugify(exerciseName),
        name: getLocalizedExerciseName(exerciseName, language),
        canonicalName: exerciseName,
        source: "core",
      });
    }
  });

  return Array.from(map.values()).sort((a, b) => a.name.localeCompare(b.name));
};

export const getExerciseDatabase = (language: SupportedLanguage = "en"): ExerciseOption[] => {
  const cached = DATABASE_CACHE[language];
  if (cached) {
    return cached;
  }

  const built = buildDatabase(language);
  DATABASE_CACHE[language] = built;
  return built;
};

export const searchExercises = (
  query: string,
  language: SupportedLanguage = "en",
  limit = 20
): ExerciseOption[] => {
  const database = getExerciseDatabase(language);
  const normalizedQuery = normalize(query);

  if (!normalizedQuery) {
    return database.slice(0, limit);
  }

  return database
    .map((item) => {
      const insight = getExerciseInsight(item.canonicalName, language);
      const searchableText = normalize(
        [
          item.name,
          item.canonicalName,
          insight.displayName,
          insight.canonicalName,
          insight.movementPattern,
          insight.movementPatternLabel,
          insight.equipment,
          insight.equipmentLabel,
          insight.difficulty,
          insight.difficultyLabel,
          ...insight.primaryMuscles,
          ...insight.secondaryMuscles,
          ...insight.primaryMuscleLabels,
          ...insight.secondaryMuscleLabels,
          ...insight.painFlags,
          ...insight.painFlagLabels,
          ...insight.techniqueCues,
        ].join(" ")
      );

      if (!searchableText.includes(normalizedQuery)) {
        return null;
      }

      let score = 0;
      if (normalize(item.name) === normalizedQuery || normalize(item.canonicalName) === normalizedQuery) {
        score += 120;
      }
      if (normalize(item.name).includes(normalizedQuery) || normalize(item.canonicalName).includes(normalizedQuery)) {
        score += 60;
      }
      if (insight.movementPattern === normalizedQuery) {
        score += 45;
      }
      if (insight.equipment === normalizedQuery) {
        score += 30;
      }
      if (insight.primaryMuscles.includes(normalizedQuery as typeof insight.primaryMuscles[number])) {
        score += 42;
      }
      if (insight.secondaryMuscles.includes(normalizedQuery as typeof insight.secondaryMuscles[number])) {
        score += 24;
      }

      score += searchableText.split(normalizedQuery).length - 1;

      return { item, score };
    })
    .filter((entry): entry is { item: ExerciseOption; score: number } => entry !== null)
    .sort((a, b) => b.score - a.score || a.item.name.localeCompare(b.item.name))
    .map((entry) => entry.item)
    .slice(0, limit);
};

const isExerciseCompatibleWithEquipment = (
  exerciseEquipment: ReturnType<typeof getExerciseInsight>["equipment"],
  availableEquipment: EquipmentAccess
): boolean => {
  if (availableEquipment === "gym") {
    return true;
  }

  if (availableEquipment === "dumbbells") {
    return (
      exerciseEquipment === "dumbbell" ||
      exerciseEquipment === "bodyweight" ||
      exerciseEquipment === "mixed"
    );
  }

  return exerciseEquipment === "bodyweight";
};

const countOverlap = (a: string[], b: string[]): number => {
  const setB = new Set(b);
  return a.reduce((acc, value) => acc + (setB.has(value) ? 1 : 0), 0);
};

export const getExerciseAlternatives = (
  exerciseName: string,
  language: SupportedLanguage = "en",
  availableEquipment: EquipmentAccess = "gym",
  limit = 10
): ExerciseOption[] => {
  const targetInsight = getExerciseInsight(exerciseName, language);
  const targetRole = inferExerciseRole(targetInsight.canonicalName, targetInsight.movementPattern);
  const normalizedTarget = normalize(targetInsight.canonicalName);
  const database = getExerciseDatabase(language);
  const directEquivalenceGroup = EQUIVALENCE_INDEX.get(normalizedTarget) ?? null;

  const scoreCandidate = (candidate: ExerciseOption, bonus = 0): number => {
    const candidateInsight = getExerciseInsight(candidate.canonicalName, language);
    const samePattern = candidateInsight.movementPattern === targetInsight.movementPattern ? 8 : 0;
    const sameEquipment = candidateInsight.equipment === targetInsight.equipment ? 3 : 0;
    const sameDifficulty = candidateInsight.difficulty === targetInsight.difficulty ? 2 : 0;
    const primaryOverlap = countOverlap(candidateInsight.primaryMuscles, targetInsight.primaryMuscles) * 4;
    const secondaryOverlap = countOverlap(candidateInsight.secondaryMuscles, targetInsight.secondaryMuscles) * 2;
    const painFlagSimilarity = countOverlap(candidateInsight.painFlags, targetInsight.painFlags);
    return bonus + samePattern + sameEquipment + sameDifficulty + primaryOverlap + secondaryOverlap + painFlagSimilarity;
  };

  const directMatches = database
    .filter((candidate) => normalize(candidate.canonicalName) !== normalizedTarget)
    .filter((candidate) => {
      if (!directEquivalenceGroup) {
        return false;
      }
      if (!directEquivalenceGroup.includes(normalize(candidate.canonicalName))) {
        return false;
      }

      const candidateInsight = getExerciseInsight(candidate.canonicalName, language);
      const candidateRole = inferExerciseRole(candidate.canonicalName, candidateInsight.movementPattern);

      if (!isRoleCompatible(targetRole, candidateRole)) {
        return false;
      }

      return isExerciseCompatibleWithEquipment(candidateInsight.equipment, availableEquipment);
    })
    .sort((a, b) => scoreCandidate(b, 50) - scoreCandidate(a, 50));

  if (directMatches.length > 0) {
    return directMatches.slice(0, limit);
  }

  return database
    .filter((candidate) => normalize(candidate.canonicalName) !== normalizedTarget)
    .map((candidate) => {
      const candidateInsight = getExerciseInsight(candidate.canonicalName, language);
      const candidateRole = inferExerciseRole(candidate.canonicalName, candidateInsight.movementPattern);

      if (!isRoleCompatible(targetRole, candidateRole)) {
        return null;
      }

      if (!isExerciseCompatibleWithEquipment(candidateInsight.equipment, availableEquipment)) {
        return null;
      }

      if (candidateInsight.movementPattern !== targetInsight.movementPattern) {
        return null;
      }

      const primaryOverlap = countOverlap(candidateInsight.primaryMuscles, targetInsight.primaryMuscles);
      const secondaryOverlap = countOverlap(candidateInsight.secondaryMuscles, targetInsight.secondaryMuscles);
      if (primaryOverlap === 0 && secondaryOverlap === 0) {
        return null;
      }

      return {
        candidate,
        score: scoreCandidate(candidate),
      };
    })
    .filter((entry): entry is { candidate: ExerciseOption; score: number } => entry !== null)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((entry) => entry.candidate);
};
